/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Infinite Canvas Image Generation API
 * Webhook-based image generation service
 * OpenAPI spec version: 2.0.0
 */
import type {
  GenerateRequest,
  GenerateResponse,
  HTTPValidationError,
} from "./models";

import { customFetch } from "./mutation";

/**
 * Initiate an image generation request.

Returns immediately with a taskId and SSE URL.
The client should connect to the SSE URL to receive real-time updates.
 * @summary Generate Image
 */
export type generateImageApiGeneratePostResponse200 = {
  data: GenerateResponse;
  status: 200;
};

export type generateImageApiGeneratePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type generateImageApiGeneratePostResponseSuccess =
  generateImageApiGeneratePostResponse200 & {
    headers: Headers;
  };
export type generateImageApiGeneratePostResponseError =
  generateImageApiGeneratePostResponse422 & {
    headers: Headers;
  };

export type generateImageApiGeneratePostResponse =
  | generateImageApiGeneratePostResponseSuccess
  | generateImageApiGeneratePostResponseError;

export const getGenerateImageApiGeneratePostUrl = () => {
  return `/api/generate`;
};

export const generateImageApiGeneratePost = async (
  generateRequest: GenerateRequest,
  options?: RequestInit,
): Promise<generateImageApiGeneratePostResponse> => {
  return customFetch<generateImageApiGeneratePostResponse>(
    getGenerateImageApiGeneratePostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(generateRequest),
    },
  );
};

/**
 * Receive webhook callbacks from Z-Image API.

Forwards the payload to the appropriate SSE connection.
 * @summary Webhook Callback
 */
export type webhookCallbackWebhookTaskIdPostResponse200 = {
  data: unknown;
  status: 200;
};

export type webhookCallbackWebhookTaskIdPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type webhookCallbackWebhookTaskIdPostResponseSuccess =
  webhookCallbackWebhookTaskIdPostResponse200 & {
    headers: Headers;
  };
export type webhookCallbackWebhookTaskIdPostResponseError =
  webhookCallbackWebhookTaskIdPostResponse422 & {
    headers: Headers;
  };

export type webhookCallbackWebhookTaskIdPostResponse =
  | webhookCallbackWebhookTaskIdPostResponseSuccess
  | webhookCallbackWebhookTaskIdPostResponseError;

export const getWebhookCallbackWebhookTaskIdPostUrl = (taskId: string) => {
  return `/webhook/${taskId}`;
};

export const webhookCallbackWebhookTaskIdPost = async (
  taskId: string,
  options?: RequestInit,
): Promise<webhookCallbackWebhookTaskIdPostResponse> => {
  return customFetch<webhookCallbackWebhookTaskIdPostResponse>(
    getWebhookCallbackWebhookTaskIdPostUrl(taskId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * SSE endpoint for clients to receive real-time updates.

Client should connect with EventSource and listen for messages.
 * @summary Sse Endpoint
 */
export type sseEndpointSseTaskIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type sseEndpointSseTaskIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type sseEndpointSseTaskIdGetResponseSuccess =
  sseEndpointSseTaskIdGetResponse200 & {
    headers: Headers;
  };
export type sseEndpointSseTaskIdGetResponseError =
  sseEndpointSseTaskIdGetResponse422 & {
    headers: Headers;
  };

export type sseEndpointSseTaskIdGetResponse =
  | sseEndpointSseTaskIdGetResponseSuccess
  | sseEndpointSseTaskIdGetResponseError;

export const getSseEndpointSseTaskIdGetUrl = (taskId: string) => {
  return `/sse/${taskId}`;
};

export const sseEndpointSseTaskIdGet = async (
  taskId: string,
  options?: RequestInit,
): Promise<sseEndpointSseTaskIdGetResponse> => {
  return customFetch<sseEndpointSseTaskIdGetResponse>(
    getSseEndpointSseTaskIdGetUrl(taskId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

export const healthHealthGet = async (
  options?: RequestInit,
): Promise<healthHealthGetResponse> => {
  return customFetch<healthHealthGetResponse>(getHealthHealthGetUrl(), {
    ...options,
    method: "GET",
  });
};
