/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Infinite Canvas Image Generation API
 * Webhook-based image generation service
 * OpenAPI spec version: 2.0.0
 */
import type {
  ChatVariationsRequest,
  ChatVariationsResponse,
  HTTPValidationError,
  SseSessionResponse,
} from "./models";

import { customFetch } from "./mutation";

/**
 * Create an SSE session for receiving webhook callbacks.

The frontend will use the returned webhookUrl when calling Kie.ai directly.
The backend never sees the user's API key.

Returns:
    SseSessionResponse: Contains sessionId, webhookUrl, and sseUrl
 * @summary Create Sse Session
 */
export type createSseSessionApiSseSessionPostResponse200 = {
  data: SseSessionResponse;
  status: 200;
};

export type createSseSessionApiSseSessionPostResponseSuccess =
  createSseSessionApiSseSessionPostResponse200 & {
    headers: Headers;
  };
export type createSseSessionApiSseSessionPostResponse =
  createSseSessionApiSseSessionPostResponseSuccess;

export const getCreateSseSessionApiSseSessionPostUrl = () => {
  return `/api/sse-session`;
};

export const createSseSessionApiSseSessionPost = async (
  options?: RequestInit,
): Promise<createSseSessionApiSseSessionPostResponse> => {
  return customFetch<createSseSessionApiSseSessionPostResponse>(
    getCreateSseSessionApiSseSessionPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * Generate multiple variations of an image prompt using AI.
 * @summary Generate Prompt Variations
 */
export type createPromptVariationsApiChatVariationsPostResponse200 = {
  data: ChatVariationsResponse;
  status: 200;
};

export type createPromptVariationsApiChatVariationsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createPromptVariationsApiChatVariationsPostResponseSuccess =
  createPromptVariationsApiChatVariationsPostResponse200 & {
    headers: Headers;
  };
export type createPromptVariationsApiChatVariationsPostResponseError =
  createPromptVariationsApiChatVariationsPostResponse422 & {
    headers: Headers;
  };

export type createPromptVariationsApiChatVariationsPostResponse =
  | createPromptVariationsApiChatVariationsPostResponseSuccess
  | createPromptVariationsApiChatVariationsPostResponseError;

export const getCreatePromptVariationsApiChatVariationsPostUrl = () => {
  return `/api/chat/variations`;
};

export const createPromptVariationsApiChatVariationsPost = async (
  chatVariationsRequest: ChatVariationsRequest,
  options?: RequestInit,
): Promise<createPromptVariationsApiChatVariationsPostResponse> => {
  return customFetch<createPromptVariationsApiChatVariationsPostResponse>(
    getCreatePromptVariationsApiChatVariationsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(chatVariationsRequest),
    },
  );
};

/**
 * Receive webhook callbacks from Z-Image API.

Forwards the payload to the appropriate SSE connection.
 * @summary Webhook Callback
 */
export type webhookCallbackWebhookTaskIdPostResponse200 = {
  data: unknown;
  status: 200;
};

export type webhookCallbackWebhookTaskIdPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type webhookCallbackWebhookTaskIdPostResponseSuccess =
  webhookCallbackWebhookTaskIdPostResponse200 & {
    headers: Headers;
  };
export type webhookCallbackWebhookTaskIdPostResponseError =
  webhookCallbackWebhookTaskIdPostResponse422 & {
    headers: Headers;
  };

export type webhookCallbackWebhookTaskIdPostResponse =
  | webhookCallbackWebhookTaskIdPostResponseSuccess
  | webhookCallbackWebhookTaskIdPostResponseError;

export const getWebhookCallbackWebhookTaskIdPostUrl = (taskId: string) => {
  return `/webhook/${taskId}`;
};

export const webhookCallbackWebhookTaskIdPost = async (
  taskId: string,
  options?: RequestInit,
): Promise<webhookCallbackWebhookTaskIdPostResponse> => {
  return customFetch<webhookCallbackWebhookTaskIdPostResponse>(
    getWebhookCallbackWebhookTaskIdPostUrl(taskId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * SSE endpoint for clients to receive real-time updates.

Client should connect with EventSource and listen for messages.
 * @summary Sse Endpoint
 */
export type sseEndpointSseTaskIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type sseEndpointSseTaskIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type sseEndpointSseTaskIdGetResponseSuccess =
  sseEndpointSseTaskIdGetResponse200 & {
    headers: Headers;
  };
export type sseEndpointSseTaskIdGetResponseError =
  sseEndpointSseTaskIdGetResponse422 & {
    headers: Headers;
  };

export type sseEndpointSseTaskIdGetResponse =
  | sseEndpointSseTaskIdGetResponseSuccess
  | sseEndpointSseTaskIdGetResponseError;

export const getSseEndpointSseTaskIdGetUrl = (taskId: string) => {
  return `/sse/${taskId}`;
};

export const sseEndpointSseTaskIdGet = async (
  taskId: string,
  options?: RequestInit,
): Promise<sseEndpointSseTaskIdGetResponse> => {
  return customFetch<sseEndpointSseTaskIdGetResponse>(
    getSseEndpointSseTaskIdGetUrl(taskId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

export const healthHealthGet = async (
  options?: RequestInit,
): Promise<healthHealthGetResponse> => {
  return customFetch<healthHealthGetResponse>(getHealthHealthGetUrl(), {
    ...options,
    method: "GET",
  });
};
