/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Infinite Canvas Image Generation API
 * Webhook-based image generation service
 * OpenAPI spec version: 2.0.0
 */

/**
 * Schema for image generation response.
 */
export interface GenerateResponse {
  taskId: string;
  sseUrl: string;
  zTaskId: string;
}
