/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Infinite Canvas Image Generation API
 * Webhook-based image generation service
 * OpenAPI spec version: 2.0.0
 */

export type ValidationErrorCtx = { [key: string]: unknown };
